sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
before_script:
 - chmod +x ./scripts/test.sh #permission to test.sh to exec
script:
  - python setup.py sdist # check for build
  - bash scripts/test.sh #run test